version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ult_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ultfpeb123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ult_fpeb_db}
      MYSQL_USER: ${MYSQL_USER:-ultuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ultpass123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    networks:
      - ult_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ult_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      HOST: 0.0.0.0
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-ult_fpeb_db}
      DB_USER: ${MYSQL_USER:-ultuser}
      DB_PASSWORD: ${MYSQL_PASSWORD:-ultpass123}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-production-jwt-key-minimum-32-characters}
      FRONTEND_URL: http://localhost:4173
      ALLOWED_ORIGINS: http://localhost:4173,http://127.0.0.1:4173,http://frontend:4173
    ports:
      - "3001:3001"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - ult_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ult_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001/api
      USE_NGINX: "false"  # Set to "true" to use Nginx instead of Vite preview
    ports:
      - "4173:4173"
      - "80:80"  # If using Nginx
    networks:
      - ult_network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4173/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # phpMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ult_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-ultuser}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-ultpass123}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ultfpeb123}
    ports:
      - "8080:80"
    networks:
      - ult_network
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - tools  # Optional service, run with: docker-compose --profile tools up

volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local

networks:
  ult_network:
    driver: bridge
